# Generated by Django 3.1.1 on 2020-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('motpasse', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='photo')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
