# Generated by Django 3.1.1 on 2020-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='motpasse',
            field=models.CharField(max_length=256),
        ),
    ]
