# Generated by Django 3.1.1 on 2020-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datesign',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timesign',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
