# Generated by Django 3.1.1 on 2020-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200911_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_cour', models.DateTimeField(auto_now_add=True)),
                ('fin_cour', models.DateTimeField(auto_now_add=True)),
                ('date_cour', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('motpasse', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='etat',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datesign',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timesign',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
