# Generated by Django 3.1.1 on 2020-09-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200921_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='etat',
        ),
    ]
