# Generated by Django 3.1.1 on 2020-09-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200922_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaire',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
    ]
