# Generated by Django 3.1.1 on 2020-09-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200923_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horaire',
            new_name='Horaire_cour',
        ),
    ]
