# Generated by Django 3.1.1 on 2020-09-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200925_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='horaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.horaire_cour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horaire_cour',
            name='date_cour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='horaire_cour',
            name='debut_cour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horaire_cour',
            name='fin_cour',
            field=models.TimeField(),
        ),
    ]
