# Generated by Django 3.1.1 on 2020-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200927_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire_cour',
            name='date_cour',
            field=models.DateField(),
        ),
    ]
